apiVersion: "v1"
kind: "Service"
metadata:
  name: "cdk8sapp-service-c8c1da0"
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: "myk8s-app"
  type: "LoadBalancer"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "cdk8sapp-deployment-c8a6fdc5"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myk8s-app"
  template:
    metadata:
      labels:
        app: "myk8s-app"
    spec:
      containers:
        - image: "alpine"
          name: "cdk8sapp"
          ports:
            - containerPort: 8080
